apiVersion: v2
name: vm-stack
description: VictoriaMetrics Operator
type: application
version: 0.1.0
appVersion: "1"
kubeVersion: ">=1.25.0"
dependencies:
  - name: victoria-metrics-operator
    version: "0.59.0"
    repository: "./charts/victoria-metrics-operator-0.59.0.tgz"
