# https://docs.victoriametrics.com/helm/victoria-metrics-k8s-stack/#install-operator-separately
crds:
  plain: true

# For the "VictoriaMetrics - operator" Grafana dashboard.
serviceMonitor:
  enabled: true