apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: senaev-com-kv-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: senaev-com-kv-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: WEBDAV_PASSWORD
      remoteRef:
        key: senaev-com-kv
        property: WEBDAV_PASSWORD
    - secretKey: XRAY_CONFIG
      remoteRef:
        key: senaev-com-kv
        property: XRAY_CONFIG
