{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "{{ .Values.grafana.username }}"
            - name: GF_SECURITY_ADMIN_PASSWORD__FILE
              value: /var/run/secrets/grafana/GRAFANA_ADMIN_PASSWORD
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_SERVER_ROOT_URL
              value: "{{ .Values.grafana.rootUrl }}"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-volume
              mountPath: /var/lib/grafana
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning
              readOnly: true
            - name: senaev-com-kv-secrets-volume
              mountPath: /var/run/secrets/grafana
              readOnly: true
      volumes:
        - name: grafana-volume
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-provisioning
          hostPath:
            path: {{ .Values.userRootPath }}/{{ .Values.grafana.provisioningPath }}
            type: DirectoryOrCreate
        - name: senaev-com-kv-secrets-volume
          secret:
            secretName: senaev-com-kv-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
{{- end }}
