{{- if .Values.nextjs.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: nextjs-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: nextjs-app
  endpoints:
    - path: /api/metrics
      targetPort: 3000
{{- end }}
