{{- if .Values.nextjs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app
          image: {{ .Values.nextjs.image }}
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: notes
              mountPath: /app/notes-folder
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: notes
          hostPath:
            path: {{ .Values.userRootPath }}/{{ .Values.webdav.volumePath }}/data/notes-folder
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: nextjs-app
spec:
  type: ClusterIP
  selector:
    app: nextjs-app
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: nextjs-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: nextjs-app
  endpoints:
    - path: /api/metrics
      targetPort: 3000
{{- end }}
