{{- if .Values.webdav.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
  namespace: {{ .Release.Namespace }}
  labels:
    app: webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdav
  template:
    metadata:
      labels:
        app: webdav
      annotations:
        secret.reloader.stakater.com/reload: "senaev-com-kv-secrets"
    spec:
      containers:
        - name: webdav
          image: {{ .Values.webdav.image }}
          env:
            - name: AUTH_TYPE
              value: Digest
            - name: USERNAME
              value: webdav_admin
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: WEBDAV_PASSWORD
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /var/lib/dav
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.userRootPath }}/{{ .Values.webdav.volumePath }}
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: webdav
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: webdav
  ports:
    - port: 80
      targetPort: 80
{{- end }}
