{{- if .Values.xray.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xray
  namespace: {{ .Release.Namespace }}
  labels:
    app: xray
spec:
  selector:
    matchLabels:
      app: xray
  template:
    metadata:
      labels:
        app: xray
      annotations:
        secret.reloader.stakater.com/reload: "senaev-com-kv-secrets"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: xray
          image: "{{ .Values.xray.image.repository }}:{{ .Values.xray.image.tag }}"
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: config-volume
              mountPath: /etc/xray
              readOnly: true
      volumes:
        - name: config-volume
          secret:
            secretName: senaev-com-kv-secrets
            items:
              - key: XRAY_CONFIG
                path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: xray
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: xray
  ports:
    - port: 8443
      targetPort: 8443
  type: ClusterIP
{{- end }}
