{{- if .Values.xray.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xray
  namespace: {{ .Release.Namespace }}
  labels:
    app: xray
spec:
  selector:
    matchLabels:
      app: xray
  template:
    metadata:
      labels:
        app: xray
      annotations:
        secret.reloader.stakater.com/reload: "senaev-com-kv-secrets"
    spec:
      nodeSelector:
        location: de
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: xray
          image: "{{ .Values.xray.image }}"
          # Dummy env var to force CreateContainerConfigError if secret is missing
          # (to avoid initialization without secret and run when secret is in Vault)
          env:
            - name: _REQUIRED_SECRET
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: XRAY_CONFIG
                  optional: false
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: config-volume
              mountPath: /etc/xray
              readOnly: true
      volumes:
        - name: config-volume
          secret:
            secretName: senaev-com-kv-secrets
            items:
              - key: XRAY_CONFIG
                path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: xray
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: xray
  ports:
    - port: 8443
      targetPort: 8443
  # ❗️ Try to proxy via Traefik on 443 port
  type: ClusterIP
{{- end }}
