ingress:
  enabled: true
  host: vault.senaev.com
  className: traefik

vault:
  fullnameOverride: "vault"

  injector:
    enabled: false

  server:
    serviceAccount:
      create: true
      name: vault-sa
    standalone:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = true
          address = "[::]:8200"
        }
        storage "file" {
          path = "/vault/data"
        }

    service:
      enabled: true

    dataStorage:
      enabled: true
      size: 1Gi
