apiVersion: v2
name: victoria-metrics-k8s-stack
description: VictoriaMetrics K8s Stack
type: application
version: 0.1.0
appVersion: "1"
kubeVersion: ">=1.25.0"
dependencies:
  - name: victoria-metrics-k8s-stack
    version: "0.72.2"
    repository: "./charts/victoria-metrics-k8s-stack-0.72.2.tgz"