victoria-metrics-k8s-stack:
  # Victoria Metrics Operator is installed separately
  # https://docs.victoriametrics.com/helm/victoria-metrics-k8s-stack/#install-operator-separately
  victoria-metrics-operator:
    enabled: false
    crds:
      cleanup:
        enabled: false

  grafana:
    enabled: true
    nodeSelector:
      node: control-plane
    annotations:
      secret.reloader.stakater.com/reload: "senaev-com-kv-secrets"
    admin:
      existingSecret: senaev-com-kv-secrets
      userKey: GRAFANA_ADMIN_USER
      passwordKey: GRAFANA_ADMIN_PASSWORD
    ingress:
      enabled: true
      ingressClassName: traefik
      path: /
      pathType: Prefix
      hosts:
        - grafana.senaev.com
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
      tls:
        - hosts:
            - grafana.senaev.com

  vmsingle:
    spec:
      nodeSelector:
        node: control-plane

  vmagent:
    spec:
      nodeSelector:
        node: control-plane

  alertmanager:
    spec:
      nodeSelector:
        node: control-plane

  vmalert:
    spec:
      nodeSelector:
        node: control-plane

  prometheus-node-exporter:
    nodeSelector:
      node: control-plane

  kube-state-metrics:
    nodeSelector:
      node: control-plane