{
 "title": "VictoriaMetrics - single-node",
 "description": "Overview for single-node VictoriaMetrics v1.117.0 or higher",
 "tags": [ "victoriametrics" ],
 "time": { "from": "now-1w", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vm_app_version{version=~\"victoria-metrics-.*\"}, job)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\", instance=~\"$instance\"},  version)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\"}, instance)"
    }
   },
   { "name": "adhoc" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total datapoints",
   "type": "stat",
   "description": "How many datapoints are in storage",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"})"
    }
   ]
  },
  {
   "title": "Ingestion rate",
   "type": "stat",
   "description": "Shows the datapoints ingestion rate.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Read requests",
   "type": "stat",
   "description": "Shows the rate of HTTP read requests.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vm_http_requests_total{job=~\"$job\", instance=~\"$instance\", path!~\".*(/write|/metrics)\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "stat",
   "description": "Total size of available memory for VM process",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active series",
   "type": "stat",
   "description": "Shows the number of [active time series](https://docs.victoriametrics.com/victoriametrics/faq/#what-is-an-active-time-series) with new data points inserted during the last hour. High value may result in ingestion slowdown.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_cache_entries{job=~\"$job\", instance=~\"$instance\", type=\"storage/hour_metric_ids\"})"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "stat",
   "description": "Total amount of used disk space",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Bytes per point",
   "type": "stat",
   "description": "Average disk usage per datapoint.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) / sum(vm_rows{job=~\"$job\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Available CPU",
   "type": "stat",
   "description": "Total number of available CPUs for VM process",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_available_cpu_cores{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(vm_app_version{job=~\"$job\", instance=~\"$instance\"}) by(job, short_version)"
    }
   ]
  },
  {
   "title": "Uptime ($job)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(min_over_time(vm_app_version{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Datapoints ingestion rate",
   "type": "timeseries",
   "description": "How many datapoints are inserted into storage per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (type, instance) > 0",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Requests rate ($instance)",
   "type": "timeseries",
   "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_http_requests_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (path) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Active time series",
   "type": "timeseries",
   "description": "Shows the number of [active time series](https://docs.victoriametrics.com/victoriametrics/faq/#what-is-an-active-time-series) with new data points inserted during the last hour. High value may result in ingestion slowdown. \n\nSee following link for details:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_cache_entries{job=~\"$job\", instance=~\"$instance\", type=\"storage/hour_metric_ids\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query duration 0.99 quantile ($instance)",
   "type": "timeseries",
   "description": "The less time it takes is better.\n* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(vm_request_duration_seconds{job=~\"$job\", instance=~\"$instance\", quantile=\"0.99\"}) by (path) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests error rate ($instance)",
   "type": "timeseries",
   "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_http_request_errors_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job, path) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Logging rate",
   "type": "timeseries",
   "description": "Shows the rate of logging the messages by their level. Unexpected spike in rate is a good reason to check logs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(vm_log_messages_total{job=~\"$job\",instance=~\"$instance\", level!=\"info\"}[$__rate_interval])) by (job, level) > 0",
     "legendFormat": "{{job}} - {{level}}"
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "RSS memory % usage ($instance)",
     "type": "timeseries",
     "description": "How much resident memory (RAM) the process is actually using, compared to its allowed container or system limit.\n\n- Good: Below 70% most of the time, maybe spiking a bit under load.\n- Bad: Above 90% for more than 5 minutes = risk of out-of-memory (OOM) kill.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance\"}\n) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU % usage ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    process_cpu_cores_available{job=~\"$job\", instance=~\"$instance\"}\n) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RSS anonymous memory % usage ($instance)",
     "type": "timeseries",
     "description": "Share for memory allocated by the process itself. When memory usage reaches 100% it will be likely OOM-killed.\nSafe memory usage % considered to be below 80%",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_resident_memory_anon_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance\"}\n) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU pressure",
     "type": "timeseries",
     "description": "CPU pressure based on [Pressure Stall Information](https://docs.kernel.org/accounting/psi.html). Helps troubleshoot high CPU usage or throttling.\nLower is better.\n\n- waiting: The percentage of time at least one task in the process was ready to run (runnable) but couldn't get scheduled on the CPU.\n- stalled: The percentage of time all tasks in the process (except idle ones) were unable to get CPU time — a full CPU stall.\n\nIf there's a CPU burst, it's normal to see waiting or stalled > 1%. It only becomes a concern if it consistently climbs above 5–10% and aligns with latency spikes or GC slowdowns.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(process_pressure_cpu_waiting_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{job}}-{{instance}} - waiting"
      },
      {
       "expr": "sum(rate(process_pressure_cpu_stalled_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{job}}-{{instance}} - waiting"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(go_memstats_sys_bytes{job=~\"$job\", instance=~\"$instance\"}) by (job) + sum(vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by (job)",
       "legendFormat": "{{job}} - requested from system"
      },
      {
       "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}) by (job) + sum(vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by (job)",
       "legendFormat": "{{job}} - heap inuse"
      },
      {
       "expr": "sum(go_memstats_stack_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}) by (job)",
       "legendFormat": "{{job}} - stack inuse"
      },
      {
       "expr": "sum(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}) by (job)",
       "legendFormat": "{{job}} - resident"
      },
      {
       "expr": "sum(process_resident_memory_anon_bytes{job=~\"$job\", instance=~\"$instance\"}) by (job)",
       "legendFormat": "{{job}} - resident anonymous"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "CPU cores used by instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "min(process_cpu_cores_available{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory pressure",
     "type": "timeseries",
     "description": "Shows memory pressure based on [Pressure Stall Information](https://docs.kernel.org/accounting/psi.html).\nLower is better.\n\n- waiting: Time fraction where at least one thread was blocked on memory.\n- stalled: Time fraction where every thread was blocked on memory (severe pressure).\n\nIf queries slow down and both series spike, the host is likely limited by RAM or I/O throughput.\n\nSee also major page faults rate panel in Troubleshooting section if this metric continued to be high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(process_pressure_memory_waiting_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - waiting"
      },
      {
       "expr": "sum(rate(process_pressure_memory_stalled_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - stalled"
      }
     ]
    },
    {
     "title": "Disk writes/reads ($instance)",
     "type": "timeseries",
     "description": "Shows the number of bytes read/write from the storage layer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(process_io_storage_read_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - read"
      },
      {
       "expr": "sum(rate(process_io_storage_written_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - write"
      }
     ]
    },
    {
     "title": "Open FDs usage % ($instance)",
     "type": "timeseries",
     "description": "Shows the percentage of open file descriptors compared to the limit set in the OS.\nReaching the limit of open files can cause various issues and must be prevented.\n\nSee how to change limits here https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_open_fds{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    process_max_fds{job=~\"$job\", instance=~\"$instance\"}\n) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Disk write/read calls ($instance)",
     "type": "timeseries",
     "description": "Shows the number of read/write syscalls such as read, pread, write, pwrite.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(process_io_read_syscalls_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - read calls"
      },
      {
       "expr": "sum(rate(process_io_write_syscalls_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}} - write calls"
      }
     ]
    },
    {
     "title": "Goroutines ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(go_goroutines{job=~\"$job\", instance=~\"$instance\"}) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "IO pressure",
     "type": "timeseries",
     "description": "Shows IO pressure based on [Pressure Stall Information](https://docs.kernel.org/accounting/psi.html).\n\nThe lower the better.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(process_pressure_io_waiting_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{job}} - waiting"
      },
      {
       "expr": "sum(rate(process_pressure_io_stalled_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{job}} - stalled"
      }
     ]
    },
    {
     "title": "Threads ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max_over_time(process_num_threads{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP connections ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vm_tcplistener_conns{job=~\"$job\", instance=~\"$instance\"}) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "CPU spent on GC ($instance)",
     "type": "timeseries",
     "description": "Shows the percent of CPU spent on garbage collection.\n\nIf % is high, then CPU usage can be decreased by changing GOGC to higher values. Increasing GOGC value will increase memory usage, and decrease CPU usage.\n\nTry searching for keyword `GOGC` at https://docs.victoriametrics.com/victoriametrics/troubleshooting/ ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n  rate(go_gc_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) \n / rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n ) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP connections rate ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_tcplistener_accepts_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Memory allocations rate",
     "type": "timeseries",
     "description": "Shows the rate of allocations in memory. Sudden increase in allocations would mean increased pressure on Go Garbage Collector and can saturate CPU resources of the application.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(rate(go_memstats_alloc_bytes_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Go scheduling latency",
     "type": "timeseries",
     "description": "Shows the time goroutines have spent in runnable state before actually running. The lower is better.\n\nHigh values or values exceeding the threshold is usually a sign of            insufficient CPU resources or CPU throttling. \n\nVerify that service has enough CPU resources. Otherwise, the service could work unreliably with delays in processing.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(histogram_quantile(0.99, sum(rate(go_sched_latencies_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job, instance, le))) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network usage",
     "type": "timeseries",
     "description": "Shows network usage by VM:\n* Writes show traffic sent to clients\n* Reads show traffic received from clients",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "sum(rate(vm_tcplistener_read_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(name) * 8 > 0",
       "legendFormat": "read via {{name}}"
      },
      {
       "expr": "sum(rate(vm_tcplistener_written_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(name) * 8 > 0",
       "legendFormat": "write via {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Churn rate ($instance)",
     "type": "timeseries",
     "description": "Shows the rate and total number of new series created over last 24h.\n\nHigh [churn rate](https://docs.victoriametrics.com/victoriametrics/faq/#what-is-high-churn-rate) tightly connected with database performance and may result in unexpected OOM's or slow queries. It is recommended to always keep an eye on this metric to avoid unexpected [cardinality](https://docs.victoriametrics.com/victoriametrics/keyconcepts/#cardinality) \"explosions\".\n\nThe higher churn rate is, the more resources required to handle it. Consider to keep the churn rate as low as possible.\n\nGood references to read:\n* https://www.robustperception.io/cardinality-is-key\n* https://www.robustperception.io/using-tsdb-analyze-to-investigate-churn-and-cardinality",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_new_timeseries_created_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) ",
       "legendFormat": "churn rate"
      },
      {
       "expr": "sum(increase(vm_new_timeseries_created_total{job=~\"$job\", instance=~\"$instance\"}[24h]))",
       "legendFormat": "new series over 24h"
      }
     ]
    },
    {
     "title": "Slow inserts %",
     "type": "timeseries",
     "description": "The percentage of [slow inserts](https://docs.victoriametrics.com/victoriametrics/faq/#what-is-a-slow-insert) compared to the total ingestion rate. \n\nThe lower the better. \n\nIn short, slow insert is a cache miss. There are following reasons for slow inserts to go up: \n* Ingestion of completely new, not seen before time series;\n* Not enough memory to maintain big enough caches for the current workload.\n\nIf percentage remains high (>10%) during extended periods of time, then it is likely more RAM is needed for optimal handling of the current number of [active time series](https://docs.victoriametrics.com/victoriametrics/faq/#what-is-an-active-time-series). \n\nSee [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3976#issuecomment-1476883183) for details.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    rate(vm_slow_row_inserts_total{job=~\"$job\"}[$__rate_interval]) \n    / rate(vm_rows_added_to_storage_total{job=~\"$job\"}[$__rate_interval])\n)",
       "legendFormat": "slow inserts"
      }
     ]
    },
    {
     "title": "Assisted merges",
     "type": "timeseries",
     "description": "Merge assist happens when storage can't keep up with merging parts. This is usually a sign of overload for storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vm_assisted_merges_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(instance, type) > 0",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "Slow queries rate",
     "type": "timeseries",
     "description": "Slow queries rate according to `search.logSlowQueryDuration` flag, which is `5s` by default.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_slow_queries_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cache usage % by type",
     "type": "timeseries",
     "description": "Shows the percentage of used cache size from the allowed size by type. \nValues close to 100% show the maximum potential utilization.\nValues close to 0% show that cache is underutilized.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance\"} \n    /\n    vm_cache_size_max_bytes{job=~\"$job\", instance=~\"$instance\"}\n) by(type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache miss ratio ($instance)",
     "type": "timeseries",
     "description": "Shows cache miss ratio. Lower is better.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    rate(vm_cache_misses_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    rate(vm_cache_requests_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n) by (type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Samples dropped for last 1h",
     "type": "timeseries",
     "description": "Shows how many samples were ignored or dropped on insertion due to various reasons:\n* timestamp out of retention period or timestamp in future;\n* invalid metric name;\n* exceeding limit for labels length or number;\n* dropped by [relabeling configuration](https://docs.victoriametrics.com/victoriametrics/single-server-victoriametrics/#relabeling).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vm_rows_ignored_total{job=~\"$job\", instance=~\"$instance\"}[1h])) by (job, reason)",
       "legendFormat": "{{instance}} - {{reason}}"
      },
      {
       "expr": "sum(increase(vm_relabel_metrics_dropped_total{job=~\"$job\", instance=~\"$instance\"}[1h])) by(job)",
       "legendFormat": "{{job}} - relabeling"
      }
     ]
    },
    {
     "title": "Deduplication rate ($instance)",
     "type": "timeseries",
     "description": "Shows rate of deduplicated samples during [deduplication](https://docs.victoriametrics.com/victoriametrics/single-server-victoriametrics/#deduplication) or [downsampling](https://docs.victoriametrics.com/victoriametrics/single-server-victoriametrics/#downsampling), according to the configured `-dedup.minScrapeInterval` or `-downsampling.period`.\n\nShould be empty if `-dedup.minScrapeInterval` and `-downsampling.period` isn't set.\n\nDeduplication happens in two places:\n* `type=\"merge\"` - during [background merges](https://docs.victoriametrics.com/victoriametrics/single-server-victoriametrics/#storage). Deduplication during merges is permanent.\n* `type=\"select\"` - during [read queries](https://docs.victoriametrics.com/victoriametrics/keyconcepts/#query-data). Deduplication happens in-flight and has no permanent effect.\n\nThe more samples need to be deduplicated, the higher will be resource usage.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_deduplicated_samples_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job, type) >0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Non-default flags",
     "type": "table",
     "description": "Flags explicitly set to non-default values",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum(flag{is_set=\"true\", job=~\"$job\", instance=~\"$instance\"}) by(job, instance, name, value)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Restarts ($job)",
     "type": "timeseries",
     "description": "Shows the number of restarts per job. The chart can be useful to identify periodic process restarts and correlate them with potential issues or anomalies. Normally, processes shouldn't restart unless restart was inited by user. The reason of restarts should be figured out by checking the logs of each specific service. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(changes(vm_app_start_timestamp{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) > 0) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Major page faults rate",
     "type": "timeseries",
     "description": "Major page faults occur when required data is not in physical memory and must be loaded from disk (storage or swap). It usually happens with:\n- insufficient physical memory\n- active use of swap space\n- file mapping access\n\nIt may cause significant performance slowdown if sustained high.\n\nPossible workaround:\n- Extend RAM to scale up\n- Reduce swap usage by adjusting vm.swappiness",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "sum(rate(process_major_pagefaults_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datapoints ingestion rate ($instance)",
     "type": "timeseries",
     "description": "How many datapoints are inserted into storage per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_rows_inserted_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by ( job,type) > 0",
       "legendFormat": "{{job}} - {{type}}"
      }
     ]
    },
    {
     "title": "Storage full ETA ($instance)",
     "type": "timeseries",
     "description": "Shows the approx time needed to reach 100% of allowed disk capacity based on the following params:\n* free disk space (after -storage.minFreeDiskSpaceBytes);\n* row ingestion rate;\n* compression.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(vm_free_disk_space_bytes{job=~\"$job\", instance=~\"$instance\"}-vm_free_disk_space_limit_bytes{job=~\"$job\", instance=~\"$instance\"}) \n/ \nignoring(path) (\n    (rate(vm_rows_added_to_storage_total{job=~\"$job\", instance=~\"$instance\"}[1d]) - \n        sum(rate(vm_deduplicated_samples_total{job=~\"$job\", instance=~\"$instance\"}[1d])) without(type)) * \n    (\n        sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"}) without(type) /\n        sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"}) without(type)\n    )\n    +\n    rate(vm_new_timeseries_created_total{job=~\"$job\", instance=~\"$instance\"}[1d]) * \n    (\n        sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type=\"indexdb/file\"}) without(type) /\n        sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type=\"indexdb/file\"}) without(type)\n    )\n) > 0",
       "legendFormat": "min ETA"
      }
     ]
    },
    {
     "title": "Concurrent flushes on disk ($instance)",
     "type": "timeseries",
     "description": "Shows how many ongoing insertions (not API /write calls) on disk are taking place, where:\n* `max` - equal to number of CPUs;\n* `current` - current number of goroutines busy with inserting rows into underlying storage.\n\nEvery successful API /write call results into flush on disk. The `max` is an internal limit and can't be changed. It is always equal to the number of CPUs. \n\nWhen `current` hits `max` constantly, it means storage is overloaded and requires more CPU (see CPU usage) or disks with more IOPS (see disk writes and reads panels in Resource Usage row).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(vm_concurrent_insert_current{job=~\"$job\", \n    instance=~\"$instance\"}[$__rate_interval])\n)",
       "legendFormat": "current"
      },
      {
       "expr": "min(vm_concurrent_insert_capacity{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Pending datapoints ",
     "type": "timeseries",
     "description": "How many data points are in RAM queue waiting to be written into storage. The number of pending data points should be in the range from 0 to `5*<ingestion_rate>`, since VictoriaMetrics pushes pending data to persistent storage every 5 seconds. The index datapoints value in general is much lower",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vm_pending_rows{job=~\"$job\", instance=~\"$instance\", type=\"storage\"}",
       "legendFormat": "{{job}} - pending datapoints"
      },
      {
       "expr": "vm_pending_rows{job=~\"$job\", instance=~\"$instance\", type=\"indexdb\"}",
       "legendFormat": "{{job}} - pending index entries"
      }
     ]
    },
    {
     "title": "Active merges ($instance)",
     "type": "timeseries",
     "description": "The number of on-going merges in storage nodes.  It is expected to have high numbers for `storage/small` metric.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vm_active_merges{job=~\"$job\", instance=~\"$instance\"}) by(job, type)",
       "legendFormat": "{{job}} - {{type}}"
      }
     ]
    },
    {
     "title": "Merge speed",
     "type": "timeseries",
     "description": "The number of rows merged per second by storage nodes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_rows_merged_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job, type)",
       "legendFormat": "{{job}} - {{type}}"
      }
     ]
    },
    {
     "title": "Disk space usage %  ($instance)",
     "type": "timeseries",
     "description": "Shows the percentage of used disk space. It is recommended to have at least 20% of free disk space for the best performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance) /\n    (\n        sum(vm_free_disk_space_bytes{job=~\"$job\", instance=~\"$instance\"}-vm_free_disk_space_limit_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance) +\n        sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance)\n    ) \n)",
       "legendFormat": "max"
      },
      {
       "expr": "min(\n    sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance) /\n    (\n        sum(vm_free_disk_space_bytes{job=~\"$job\", instance=~\"$instance\"}-vm_free_disk_space_limit_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance) +\n        sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance)\n    ) \n)",
       "legendFormat": "min"
      },
      {
       "expr": "quantile(0.5,\n    sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance) /\n    (\n        sum(vm_free_disk_space_bytes{job=~\"$job\", instance=~\"$instance\"}-vm_free_disk_space_limit_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance) +\n        sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance)\n    ) \n)",
       "legendFormat": "median"
      }
     ]
    },
    {
     "title": "LSM parts max by type ($instance)",
     "type": "timeseries",
     "description": "The max number of data parts of LSM tree across all storage nodes in the last [partition](https://docs.victoriametrics.com/victoriametrics/single-server-victoriametrics/#storage).\nIncrease in number of parts (the hard limit is 512) is an evidence of slow merge performance - check the resource utilization.\n* `indexdb` - inverted index\n* `storage/small` - recently added parts of data ingested into storage (hot data)\n* `storage/big` -  small parts gradually merged into bigger parts (cold data)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vm_parts{job=~\"$job\", instance=~\"$instance\", type=~\"indexdb.*\"}) by (job, type)",
       "legendFormat": "{{job}} - {{type}}"
      },
      {
       "expr": "max(vm_last_partition_parts{job=~\"$job\", instance=~\"$instance\"}) by(job, type)",
       "legendFormat": "{{job}} - {{type}}"
      }
     ]
    },
    {
     "title": "Disk space usage % by type  ($instance)",
     "type": "timeseries",
     "description": "Shows the percentage of used disk space by type: datapoints or indexdb. Normally, indexdb takes much less space comparing to datapoints. But with high [churn rate](https://docs.victoriametrics.com/victoriametrics/faq/#what-is-high-churn-rate) the size of the indexdb could grow significantly.\n\nThe sum of the % can be > 100% since panel shows max % per-job and per-instance. It means different instance can have different ratio between datapoints and indexdb size.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type=~\"indexdb.*\"}) by(job, instance)\n    / \n    sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance)\n)",
       "legendFormat": "indexdb"
      },
      {
       "expr": "max(\n    sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"}) by(job, instance)\n    / \n    sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance)\n)",
       "legendFormat": "datapoints"
      }
     ]
    },
    {
     "title": "Disk space usage - datapoints",
     "type": "timeseries",
     "description": "Shows amount of on-disk space occupied by data points and the remaining disk space at `-storageDataPath`. Calculation accounts for -storage.minFreeDiskSpaceBytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"}) by (job)",
       "legendFormat": "{{job}} - Used (datapoints)"
      },
      {
       "expr": "vm_free_disk_space_bytes{job=~\"$job\", instance=~\"$instance\"} - vm_free_disk_space_limit_bytes{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{job}} - Free"
      },
      {
       "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type=~\"indexdb.*\"}) by (job)",
       "legendFormat": "{{job}} - Used (index)"
      }
     ]
    },
    {
     "title": "Datapoints",
     "type": "timeseries",
     "description": "Shows how many datapoints are in the storage and what is average disk usage per datapoint.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"}) by (job)",
       "legendFormat": "{{job}} - total datapoints"
      },
      {
       "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by (job)\n/ sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"}) by (job)",
       "legendFormat": "{{job}} - bytes-per-datapoint"
      }
     ]
    },
    {
     "title": "Pending datapoints ($instance)",
     "type": "timeseries",
     "description": "How many data points are in RAM queue waiting to be written into storage. The number of pending data points should be in the range from 0 to `5*<ingestion_rate>`, since VictoriaMetrics pushes pending data to persistent storage every 5 seconds. The index datapoints value in general is much lower.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max_over_time(vm_pending_rows{job=~\"$job\", instance=~\"$instance\", type=\"storage\"}[$__rate_interval]))",
       "legendFormat": "pending datapoints"
      },
      {
       "expr": "sum(max_over_time(vm_pending_rows{job=~\"$job\", instance=~\"$instance\", type=\"indexdb\"}[$__rate_interval]))",
       "legendFormat": "pending index entries"
      }
     ]
    },
    {
     "title": "Rows ignored for last 1h",
     "type": "timeseries",
     "description": "Shows how many rows were ignored on insertion due to corrupted or out of retention timestamps and how many series were ignored on insertion or during scrape due to too long label names, values and excessive labels count.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vm_rows_ignored_total{job=~\"$job\", instance=~\"$instance\"}[1h])) by (instance, reason)",
       "legendFormat": "{{instance}} - {{reason}}"
      }
     ]
    },
    {
     "title": "Datapoints read per series",
     "type": "timeseries",
     "description": "99th percentile of number of [data samples](https://docs.victoriametrics.com/victoriametrics/keyconcepts/#raw-samples) read per queried series.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(vm_rows_read_per_series_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job, vmrange))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Concurrent flushes on disk {$instance}",
     "type": "timeseries",
     "description": "Shows how many ongoing insertions (not API /write calls) on disk are taking place, where:\n* `max` - equal to number of CPUs;\n* `current` - current number of goroutines busy with inserting rows into underlying storage.\n\nEvery successful API /write call results into flush on disk. However, these two actions are separated and controlled via different concurrency limiters. The `max` on this panel can't be changed and always equal to number of CPUs. \n\nWhen `current` hits `max` constantly, it means storage is overloaded and requires more CPU.\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max_over_time(vm_concurrent_insert_capacity{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - max"
      },
      {
       "expr": "sum(vm_concurrent_insert_current{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}} - current"
      }
     ]
    },
    {
     "title": "Datapoints scanned per query",
     "type": "timeseries",
     "description": "99th percentile of number of [data samples](https://docs.victoriametrics.com/victoriametrics/keyconcepts/#raw-samples) scanner per query.\n\nThis number can exceed number of RowsReadPerQuery if `step` query arg passed to [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) is smaller than the lookbehind window set in square brackets of [rollup function](https://docs.victoriametrics.com/victoriametrics/metricsql/#rollup-functions). For example, if `increase(some_metric[1h])` is executed with the `step=5m`, then the same [data samples](https://docs.victoriametrics.com/victoriametrics/keyconcepts/#raw-samples) on a hour time range are scanned `1h/5m=12` times. See [this article](https://valyala.medium.com/how-to-optimize-promql-and-metricsql-queries-85a1b75bf986) for details.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(vm_rows_scanned_per_query_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job, vmrange))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Series read per query",
     "type": "timeseries",
     "description": "99th percentile of number of series read per query.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(vm_series_read_per_query_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job, vmrange))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Datapoints read per query",
     "type": "timeseries",
     "description": "99th percentile of number of [data samples](https://docs.victoriametrics.com/victoriametrics/keyconcepts/#raw-samples) read per query.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(vm_rows_read_per_query_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job, vmrange))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Number of snapshots",
     "type": "timeseries",
     "description": "Shows number of existing [snapshots](https://docs.victoriametrics.com/victoriametrics/single-server-victoriametrics/#how-to-work-with-snapshots).\n\nRecently made snapshots do not occupy disk space. But with time, as snapshots become older, they start to occupy more and more disk space.\n\nIt is recommended deleting old snapshots when they are no longer needed to free up disk space.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vm_snapshots{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 17, "x": 0, "y": 427 },
     "options": {
      "content": "Drilldown row is used by other panels on the dashboard to show more detailed metrics per-instance, or a single instance in cases like memory breakdown."
     }
    },
    {
     "title": "Major page faults rate",
     "type": "timeseries",
     "description": "Major page faults occur when required data is not in physical memory and must be loaded from disk (storage or swap). It usually happens with:\n- insufficient physical memory\n- active use of swap space\n- file mapping access\n\nIt may cause significant performance slowdown if sustained high.\n\nPossible workaround:\n- Extend RAM to scale up\n- Reduce swap usage by adjusting vm.swappiness",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 429 },
     "targets": [
      {
       "expr": "sum(rate(process_major_pagefaults_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job,instance)",
       "legendFormat": "{{instance}} ({{job}})"
      }
     ]
    },
    {
     "title": "Memory usage breakdown",
     "type": "timeseries",
     "description": "This panel breaks down memory usage by type. It’s intended for inspecting a single instance.\n\nHow to use:\n- Start from the high-level RSS panel.\n- Identify an instance with unexpected or abnormal memory growth.\n- Filter to that instance to inspect the detailed breakdown.\n\nInterpretation\n- A steadily rising Go Heap usually indicates a memory leak. Collect pprof memory profile.\n- A growing Go Stack commonly points to a goroutine leak.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 429 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "# go other\nmax(\n    go_memstats_gc_sys_bytes{job=~\"$job\", instance=~\"$instance\"} +\n    go_memstats_mspan_sys_bytes{job=~\"$job\", instance=~\"$instance\"} +\n    go_memstats_other_sys_bytes{job=~\"$job\", instance=~\"$instance\"} +\n    go_memstats_mcache_sys_bytes{job=~\"$job\", instance=~\"$instance\"}\n)",
       "legendFormat": "Go: Other"
      },
      {
       "expr": "# go stack\nmax(go_memstats_stack_inuse_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "Go: Stack"
      },
      {
       "expr": "#go heap inuse\nmax(\n    go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}\n    +\n    (\n        go_memstats_heap_idle_bytes{job=~\"$job\", instance=~\"$instance\"}\n        -\n        go_memstats_heap_released_bytes{job=~\"$job\", instance=~\"$instance\"}\n    )\n)",
       "legendFormat": "Go: Heap"
      },
      {
       "expr": "# go heap reserved\nmax(go_memstats_heap_released_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "Go: Heap Reserved"
      },
      {
       "expr": "# vm cache\nmax(sum(vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by (job, instance))",
       "legendFormat": "Mmap: VM Cache"
      },
      {
       "expr": "# file pages\nmax(process_resident_memory_file_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "File cache"
      }
     ]
    },
    {
     "title": "RSS memory usage ($instance)",
     "type": "timeseries",
     "description": "Shows the used memory (resident).\nThe application's performance will significantly degrade when memory usage is close to 100%.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 437 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max_over_time(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} ({{job}})"
      }
     ]
    },
    {
     "title": "RSS anonymous memory usage ($instance)",
     "type": "timeseries",
     "description": "RSS share for memory allocated by the process itself. This share cannot be freed by the OS, so it must be taken into account by OOM killer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 437 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max_over_time(process_resident_memory_anon_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} ({{job}})"
      }
     ]
    },
    {
     "title": "Storage full ETA ($instance)",
     "type": "timeseries",
     "description": "Shows the approx time needed to reach 100% of allowed disk capacity based on the following params:\n* free disk space (after -storage.minFreeDiskSpaceBytes);\n* row ingestion rate;\n* compression.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 445 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(vm_free_disk_space_bytes{job=~\"$job\", instance=~\"$instance\"}-vm_free_disk_space_limit_bytes{job=~\"$job\", instance=~\"$instance\"}) \n/ \nignoring(path) (\n    (rate(vm_rows_added_to_storage_total{job=~\"$job\", instance=~\"$instance\"}[1d]) - \n        sum(rate(vm_deduplicated_samples_total{job=~\"$job\", instance=~\"$instance\"}[1d])) without(type)) * \n    (\n        sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"}) without(type) /\n        sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"}) without(type)\n    )\n    +\n    rate(vm_new_timeseries_created_total{job=~\"$job\", instance=~\"$instance\"}[1d]) * \n    (\n        sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type=\"indexdb/file\"}) without(type) /\n        sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type=\"indexdb/file\"}) without(type)\n    )\n) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU usage ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 445 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job, instance)",
       "legendFormat": "{{instance}} ({{job}})"
      }
     ]
    },
    {
     "title": "Disk space usage by type ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 453 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type=~\"indexdb.*\"}) by(job, instance)",
       "legendFormat": "{{job}}:{{instance}} (indexdb)"
      },
      {
       "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"}) by(job, instance)",
       "legendFormat": "{{job}}:{{instance}} (datapoints)"
      }
     ]
    },
    {
     "title": "Disk space usage ($instance)",
     "type": "timeseries",
     "description": "Shows the percentage of used disk space. It is recommended to have at least 20% of free disk space for the best performance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 453 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by(job, instance)"
      }
     ]
    },
    {
     "title": "Logging rate",
     "type": "timeseries",
     "description": "Shows the rate of logging the messages by their level. Unexpected spike in rate is a good reason to check logs.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 461 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_log_messages_total{job=~\"$job\",instance=~\"$instance\", level!=\"info\"}[$__rate_interval])) by (job, instance, level, location) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}