apiVersion: v2
name: external-secrets
description: External Secrets Operator (installed before vault so CRDs exist)
type: application
version: 0.1.0
kubeVersion: ">=1.25.0"
dependencies:
  - name: external-secrets
    version: "2.0.1"
    repository: "file://./charts/external-secrets-2.0.1.tgz"
