apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: {{ .Release.Namespace }}
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: "{{ .Values.image }}"
          args:
            - "--log.level=INFO"
            - "--accesslog=true"
            - "--accesslog.filepath=/dev/stdout"
            - "--providers.kubernetesingress=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
            - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.letsencrypt.acme.email={{ .Values.acme.email }}"
            - "--certificatesresolvers.letsencrypt.acme.storage=/acme-data/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
          volumeMounts:
            - name: acme-data
              mountPath: /acme-data
              readOnly: false
      volumes:
        - name: acme-data
          hostPath:
            path: {{ .Values.userRootPath }}/k3s-cluster/volumes/traefik-acme
            type: DirectoryOrCreate
